schema_version: "1.0"

reviews:
  enabled: true
  auto_review:
    base_branches:
      - "dev"
      - "test"
    ignore_title_keywords:
      - "WIP"
  limit_reviews_by_label:
    - "documentation"
  path_filters:
    - "!*.html"
    - "!*.mdx"
  path_instructions:
    - path: "**/*.mdx"
      instructions: |
        Ensure consistency in terminology and formatting across all documentation files.
        Cross-check references and links against other markdown files in the repository.
chat:
  auto_reply: true
  integrations: {}
 
tone_instructions: "Provide concise and constructive feedback on documentation clarity and consistency."
knowledge_base:
  opt_out: false
  web_search:
    enabled: true

finishing_touches:
  docstrings:
    enabled: false
  unit_tests:
    enabled: false
