import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  userDocs: [
    {
      type: "category",
      label: "About",
      collapsed: false,
      items: [
        'about/introduction',
        'about/components',
        'about/features',
        'about/benchmarks',
        'about/comparisons',
        'about/licensing',
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        'getting-started/single-node-deployment',
        'getting-started/cluster-deployment',
        'getting-started/virtual-ip-address',
        'getting-started/devices',
        'getting-started/targets',
        'getting-started/routes',
        'getting-started/pipelines',
        'getting-started/multi-event-routing',
      ],
    },
    {
      type: "category",
      label: "Deployment",
      link: {type: "doc", id: "deployment/index"},
      items: [
        'deployment/local',
        'deployment/azure-vm',
        'deployment/azure-app-service',
        'deployment/azure-functions',
        'deployment/azure-arc-extension',
      ],
    },
    {
      type: "category",
      label: "Migration",
      items: [
        'migration/cribl',
        'migration/tenzir',
        'migration/vector',
        'migration/logstash',
      ],
    },
    {
      type: "category",
      label: "Architecture",
      items: [
        'architecture/overview',
        'architecture/clustering',
        'architecture/file-system',
        'architecture/persistency',
        'architecture/zero-trust',
        {
          type: "category",
          label: "Microsoft Sentinel",
          items: [
            "architecture/microsoft-sentinel/overview",
            {
              type: "category",
              label: "Integration",
              items: [
                'architecture/microsoft-sentinel/integration/autodiscovery',
                'architecture/microsoft-sentinel/integration/manual',
              ],
            },
            {
              type: "category",
              label: "Automation",
              items: [
                'architecture/microsoft-sentinel/automation/arm-templates',
                'architecture/microsoft-sentinel/automation/bicep-templates',
              ],
            },
            {
              type: "category",
              label: "Content Hub",
              items: [
                'architecture/microsoft-sentinel/content-hub/checkpoint',
                'architecture/microsoft-sentinel/content-hub/fortigate',
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      link: {type: "doc", id: "configuration/index"},
      items: [
        {
          type: "category",
          label: "Devices",
          link: {type: "doc", id: "configuration/devices/index"},
          items: [
            "configuration/devices/windows",
            "configuration/devices/linux",
            "configuration/devices/syslog",
            "configuration/devices/snmp-trap",
            "configuration/devices/estreamer",
            "configuration/devices/http",
            "configuration/devices/tcp",
            "configuration/devices/udp",
            "configuration/devices/smtp",
            "configuration/devices/tftp",
            "configuration/devices/kafka",
            "configuration/devices/nats",
            "configuration/devices/rabbitmq",
            "configuration/devices/redis",
            "configuration/devices/netflow",
            "configuration/devices/sflow",
            "configuration/devices/ipfix",
            "configuration/devices/ms-sentinel",
            "configuration/devices/azure-monitor",
          ],
        },
        {
          type: "category",
          label: "Pipelines",
          link: {type: "doc", id: "configuration/pipelines/index"},
          items: [
            "configuration/pipelines/pre-processing",
            "configuration/pipelines/normalization",
            "configuration/pipelines/post-processing",
            {
              type: "category",
              label: "Processors",
              link: {type: "doc", id: "configuration/pipelines/processors/index"},
              items: [
                "configuration/pipelines/processors/alienvault",
                "configuration/pipelines/processors/anthropic",
                "configuration/pipelines/processors/append",
                "configuration/pipelines/processors/attachment",
                "configuration/pipelines/processors/azureai",
                "configuration/pipelines/processors/bytes",
                "configuration/pipelines/processors/cef",
                "configuration/pipelines/processors/circle",
                "configuration/pipelines/processors/cloudflare",
                "configuration/pipelines/processors/comment",
                "configuration/pipelines/processors/community_id",
                "configuration/pipelines/processors/compact",
                "configuration/pipelines/processors/contains",
                "configuration/pipelines/processors/convert",
                "configuration/pipelines/processors/csv",
                "configuration/pipelines/processors/date",
                "configuration/pipelines/processors/date_index_name",
                "configuration/pipelines/processors/decrypt",
                "configuration/pipelines/processors/dissect",
                "configuration/pipelines/processors/dns_lookup",
                "configuration/pipelines/processors/dot_expander",
                "configuration/pipelines/processors/dot_nester",
                "configuration/pipelines/processors/drop",
                "configuration/pipelines/processors/encrypt",
                "configuration/pipelines/processors/enrich",
                "configuration/pipelines/processors/fail",
                "configuration/pipelines/processors/final",
                "configuration/pipelines/processors/fingerprint",
                "configuration/pipelines/processors/foreach",
                "configuration/pipelines/processors/geo_grid",
                "configuration/pipelines/processors/geoip",
                "configuration/pipelines/processors/grok",
                "configuration/pipelines/processors/gsub",
                "configuration/pipelines/processors/html_strip",
                "configuration/pipelines/processors/ipqualityscore",
                "configuration/pipelines/processors/join",
                "configuration/pipelines/processors/json",
                "configuration/pipelines/processors/kv",
                "configuration/pipelines/processors/leef",
                "configuration/pipelines/processors/level",
                "configuration/pipelines/processors/lookup",
                "configuration/pipelines/processors/lowercase",
                "configuration/pipelines/processors/mask",
                "configuration/pipelines/processors/move",
                "configuration/pipelines/processors/network_direction",
                "configuration/pipelines/processors/normalize",
                "configuration/pipelines/processors/openai",
                "configuration/pipelines/processors/pattern",
                "configuration/pipelines/processors/pipeline",
                "configuration/pipelines/processors/redact",
                "configuration/pipelines/processors/regex_extract",
                "configuration/pipelines/processors/regex_filter",
                "configuration/pipelines/processors/registered_domain",
                "configuration/pipelines/processors/remove",
                "configuration/pipelines/processors/rename",
                "configuration/pipelines/processors/reroute",
                "configuration/pipelines/processors/script",
                "configuration/pipelines/processors/set",
                "configuration/pipelines/processors/sort",
                "configuration/pipelines/processors/split",
                "configuration/pipelines/processors/syslog",
                "configuration/pipelines/processors/trim",
                "configuration/pipelines/processors/uppercase",
                "configuration/pipelines/processors/uri_parts",
                "configuration/pipelines/processors/urldecode",
                "configuration/pipelines/processors/user_agent",
                "configuration/pipelines/processors/virustotal",
                "configuration/pipelines/processors/xml",
              ],
            },
            "configuration/pipelines/conditional-running",
            "configuration/pipelines/handling-failures",
            "configuration/pipelines/handling-success",
          ],
        },
        {
          type: "category",
          label: "Routes",
          link: {type: "doc", id: "configuration/routes/index"},
          items: [
            'configuration/routes/management',
          ],
        },
        {
          type: "category",
          label: "Targets",
          link: {type: "doc", id: "configuration/targets/index"},
          items: [
            "configuration/targets/ms-sentinel",
            "configuration/targets/azure-data-explorer",
            "configuration/targets/azure-blob-storage",
            "configuration/targets/splunk-hec",
            "configuration/targets/elasticsearch",
            "configuration/targets/file",
            "configuration/targets/syslog",
            "configuration/targets/console",
            "configuration/targets/discard",
          ],
        },
      ],
    },
    "appendix",
    "glossary"
  ],
  tutorDocs: [
    "tutorials/overview",
    "tutorials/syslog-to-console",
    "tutorials/syslog-to-parquet-file",
  ],
};

export default sidebars;
